### Apply Bayes' Theorem to solve a medical diagnosis problem given conditional probabilities.Find the eigenvalues and corresponding eigenvectors of a given matrix.Calculate the determinant of a 3x3 matrix and find its inverse if possible.Describe the properties and applications of the Normal distribution and calculate probabilities using its properties

Here I'll use a hypothetical example where we want to determine the probability that a person has diabetes given that they tested positive.
Bayes' Theorem is stated as:
P(D∣T)= P(T∣D)⋅P(D)+P(T∣¬D)⋅P(¬D)/P(T∣D)⋅P(D)
​

​Where:

P(D∣T): Probability that the person has diabetes given a positive test result (posterior probability).

P(T∣D): Probability that the test is positive given that the person has diabetes (sensitivity or true positive rate).

P(D): Probability that a randomly selected person has diabetes (prior probability).

P(¬D): Probability that a randomly selected person does not have diabetes (1 - prior probability).

P(T∣¬D): Probability that the test is positive given that the person does not have diabetes (false positive rate).
 
Example:

P(D)=0.10: 10% of the population has diabetes.

P(T∣D)=0.90: If a person has diabetes, there’s a 90% chance the test will be positive.

P(T∣¬D)=0.05: If a person does not have diabetes, there’s a 5% chance the test will still be positive.

P(¬D)=0.90: 90% of the population does not have diabetes.

Using these values, we can calculate the probability that a person has diabetes given a positive test result.


In [4]:
P_D = 0.10       # Prior probability of having diabetes
P_not_D = 1 - P_D # Prior probability of not having diabetes

P_T_given_D = 0.90  # Probability of testing positive given diabetes (sensitivity)
P_T_given_not_D = 0.05  # Probability of testing positive given no diabetes (false positive rate)

# Applying Bayes' Theorem
P_D_given_T = (P_T_given_D * P_D) / ((P_T_given_D * P_D) + (P_T_given_not_D * P_not_D))


print(f"The probability that a person has diabetes given a positive test result is: {P_D_given_T:.2%}")


The probability that a person has diabetes given a positive test result is: 66.67%


Eigenvalues and Eigenvectors
Given a square matrix 𝐴, an eigenvalue 
𝜆 and an associated eigenvector 
𝑣 satisfy the equation: Av=λv
This equation can be rewritten as: (A−λI)v=0
Where:

𝐴is the square matrix.
𝜆 is the eigenvalue.
𝑣 is the eigenvector associated with the eigenvalue 𝜆.
𝐼 is the identity matrix of the same dimension as 𝐴.
To find the eigenvalues, we solve the characteristic equation:


det(A−λI)=0
Once the eigenvalues 𝜆 are found, we substitute each back into the equation (A−λI)v=0 to solve for the eigenvectors 𝑣.


  
​
Example:
Let's consider the matrix:




In [23]:
import numpy as np

# Define the matrix A
A = np.array([[4, 1, 6],
              [2, 5, 7],
              [2, 8, 9]])

# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)


print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[16.01789412  2.30685995 -0.32475407]

Eigenvectors:
[[-0.41131305 -0.96297319 -0.66712795]
 [-0.54081519  0.01556299 -0.48863069]
 [-0.73371691  0.26914758  0.56229916]]


Let's calculate the determinant of a 3x3 matrix and, if the determinant is non-zero, find the inverse of the matrix. I'll walk through the steps and provide the Python code to do this.

In [14]:
import numpy as np

# Define the matrix A
A = np.array([[2, 4, 6],
              [1, -2, 3],
              [0, 5, -1]])

# Calculate the determinant
det_A = np.linalg.det(A)

# Display the determinant
print(f"Determinant of A: {det_A:.2f}")

# Check if the determinant is non-zero
if det_A != 0:
    # Calculate the inverse
    A_inv = np.linalg.inv(A)
    print("\nInverse of A:")
    print(A_inv)
else:
    print("\nThe matrix is singular and does not have an inverse.")


Determinant of A: 8.00

Inverse of A:
[[-1.625  4.25   3.   ]
 [ 0.125 -0.25   0.   ]
 [ 0.625 -1.25  -1.   ]]


Properties of the Normal Distribution
The Normal distribution, also known as the Gaussian distribution, is a continuous probability distribution that is widely used in statistics. Here are the key properties:

Symmetry:

The Normal distribution is symmetric about its mean μ. This means that the left side of the distribution is a mirror image of the right side.
Bell-Shaped Curve:

The probability density function (PDF) of a Normal distribution forms a bell-shaped curve. The highest point on the curve corresponds to the mean μ.
Mean, Median, and Mode:

In a Normal distribution, the mean, median, and mode are all equal and located at the center of the distribution.
Standard Deviation:

The standard deviation σ determines the spread of the distribution. A smaller 𝜎 results in a steeper curve, while a larger 𝜎results in a flatter curve.
68-95-99.7 Rule (Empirical Rule):

About 68% of the data falls within one standard deviation (μ±σ) of the mean.
About 95% of the data falls within two standard deviations (μ±2σ) of the mean.
About 99.7% of the data falls within three standard deviations (μ±3σ) of the mean.
Asymptotic:

The tails of the Normal distribution extend infinitely in both directions and approach, but never touch, the horizontal axis.
Defined by Mean and Standard Deviation:

A Normal distribution is completely defined by its mean 𝜇 and standard deviation σ.
Applications of the Normal Distribution
The Normal distribution has numerous applications across various fields:

Statistical Inference:

Many statistical tests, such as t-tests and ANOVA, are based on the assumption that the data follows a Normal distribution.
Central Limit Theorem:

The Central Limit Theorem states that the distribution of the sum (or average) of a large number of independent, identically distributed random variables tends to follow a Normal distribution, regardless of the original distribution of the variables.
Quality Control:

In manufacturing, the Normal distribution is used in quality control processes to monitor whether products meet certain specifications.
Finance:

Asset returns are often modeled using the Normal distribution. Many financial models, such as the Black-Scholes option pricing model, assume that returns are normally distributed.
Natural Phenomena:

Many natural phenomena, such as heights, weights, and IQ scores, tend to follow a Normal distribution.

Calculating Probabilities Using the Normal Distribution
Let's calculate some probabilities using the properties of the Normal distribution.

Example:
Suppose the weights of a certain population follow a Normal distribution with a mean μ=70 kg and a standard deviation σ=10 kg. We want to calculate the following probabilities:

P(X < 80): The probability that a randomly selected person weighs less than 80 kg.
P(60 < X < 90): The probability that a randomly selected person weighs between 60 kg and 90 kg.

In [18]:
import scipy.stats as stats

s
mu = 70  # mean
sigma = 10  

# 1. P(X < 80)
prob_less_than_80 = stats.norm.cdf(80, mu, sigma)
print(f"P(X < 80): {prob_less_than_80:.4f}")

# 2. P(60 < X < 90)
prob_between_60_and_90 = stats.norm.cdf(90, mu, sigma) - stats.norm.cdf(60, mu, sigma)
print(f"P(60 < X < 90): {prob_between_60_and_90:.4f}")


P(X < 80): 0.8413
P(60 < X < 90): 0.8186
